name: cucumber_dart
description: A cucumber implementation for Dart.
version: 1.0.0
repository: https://github.com/PiotrFLEURY/cucumber_dart
publish_to: none

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  file: ^7.0.0
  test: ^1.24.0

dev_dependencies:
  lints: ^2.1.0
